const app=document.getElementById("app"), modal=document.getElementById("modal"), toast=document.getElementById("toast");
let me=null, state={q:"",category:"all",condition:"all",sort:"newest"};

const categories=[["all","All"],["electronics","📱 Electronics"],["books","📚 Books"],["furniture","🪑 Furniture"],["clothes","👕 Clothes"],["gaming","🎮 Gaming"],["appliances","🍳 Appliances"],["sports","🏋️ Sports"],["others","📦 Others"]];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=n=>"₹"+Number(n).toLocaleString("en-IN");
async function api(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Something went wrong");return d}
function showToast(s){toast.textContent=s;toast.className="show";setTimeout(()=>toast.className="",2500)}
function modalBox(html){modal.innerHTML=`<div class="modalbox"><button class="close" onclick="modal.classList.add('hidden')">×</button>${html}</div>`;modal.classList.remove("hidden")}
async function loadMe(){try{me=(await api("/api/auth/me")).user}catch{me=null} updateAuth()}
function updateAuth(){document.getElementById("authBtn").textContent=me?`Hi, ${me.name.split(" ")[0]}`:"Login"}
function card(x){return `<article class="card" onclick="location.hash='#/item/${x._id}'"><div class="pic">${x.images?.[0]?`<img src="${x.images[0]}">`:`<div class="placeholder">📦</div>`}<span class="badge">${x.urgent?"🚨 Urgent":esc(x.condition)}</span><button class="heart" onclick="event.stopPropagation();save('${x._id}')">♡</button></div><div class="card-body"><h3>${esc(x.title)}</h3><div class="row"><span class="price">${money(x.price)}</span><span class="muted">${esc(x.category)}</span></div><p class="muted">${esc(x.location||"Hostel campus")}</p></div></article>`}
async function home(){
  app.innerHTML=`<section class="hero"><div><div class="muted" style="color:#bcb5df">YOUR HOSTEL. YOUR MARKET.</div><h1>Buy & sell anything with people you already trust.</h1><p>HostelX is a private student marketplace for books, electronics, furniture, gaming gear and everyday hostel items.</p><button class="primary" onclick="sell()">+ List an item</button></div><div class="hero-card"><b>Why HostelX?</b><p>✓ Student-focused marketplace<br>✓ Pickup inside campus<br>✓ Seller profiles & ratings<br>✓ Report suspicious listings</p></div></section><div class="wrap"><div class="cats">${categories.map(c=>`<button class="cat ${state.category===c[0]?"active":""}" onclick="state.category='${c[0]}';home()">${c[1]}</button>`).join("")}</div><div class="toolbar"><h2>Latest listings</h2><div class="filters"><select onchange="state.condition=this.value;home()"><option value="all">All conditions</option><option>New</option><option>Like New</option><option>Good</option><option>Used</option></select><select onchange="state.sort=this.value;home()"><option value="newest">Newest</option><option value="priceLow">Lowest price</option><option value="priceHigh">Highest price</option></select></div></div><div id="items" class="grid"></div></div><div class="footer">HostelX © 2026 · Built for campus communities</div>`;
  try{const q=new URLSearchParams({q:state.q,category:state.category,condition:state.condition,sort:state.sort});const data=await api("/api/listings?"+q);document.getElementById("items").innerHTML=data.length?data.map(card).join(""):`<div class="empty" style="grid-column:1/-1">No listings found. Be the first to list something!</div>`}catch(e){showToast(e.message)}
}
async function item(id){
  try{const x=await api("/api/listings/"+id);app.innerHTML=`<div class="wrap"><button class="ghost" onclick="history.back()">← Back</button><div class="detail" style="margin-top:18px"><div class="gallery">${x.images?.length?`<img id="mainimg" class="mainimg" src="${x.images[0]}"><div class="thumbs">${x.images.map(i=>`<img src="${i}" onclick="mainimg.src='${i}'">`).join("")}</div>`:`<div class="mainimg placeholder">📦</div>`}</div><div class="panel"><span class="muted">${esc(x.category)} · ${esc(x.condition)}</span><h1>${esc(x.title)}</h1><div class="price">${money(x.price)}</div>${x.originalPrice?`<span class="muted">Original price: ${money(x.originalPrice)}</span>`:""}<p>${esc(x.description)}</p><p class="muted">📍 ${esc(x.location||"Hostel campus")}</p><div class="actions"><button class="primary wide" onclick="contact('${x._id}')">💬 Contact seller</button><button class="ghost" onclick="save('${x._id}')">♥</button></div><button class="danger wide" onclick="report('${x._id}')">Report listing</button><div class="seller"><b>Seller</b><p>${esc(x.seller?.name||"Student")} ${x.seller?.verified?"✓":""}</p><span class="muted">⭐ ${x.seller?.rating||5} · Member since ${x.seller?.createdAt?new Date(x.seller.createdAt).getFullYear():"2026"}</span></div></div></div></div>`}catch(e){app.innerHTML=`<div class="empty">${esc(e.message)}</div>`}
}
function login(){modalBox(`<h2>Welcome back</h2><form class="form" onsubmit="doLogin(event)"><label>Email<input id="email" type="email" required></label><label>Password<input id="password" type="password" required></label><button class="primary">Login</button><p class="muted">New here? <a href="#" onclick="register();return false">Create account</a></p></form>`)}
async function doLogin(e){e.preventDefault();try{await api("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email.value,password:password.value})});modal.classList.add("hidden");await loadMe();showToast("Logged in");route()}catch(x){showToast(x.message)}}
function register(){modalBox(`<h2>Create your HostelX account</h2><form class="form" onsubmit="doRegister(event)"><label>Name<input id="rname" required></label><div class="two"><label>Student ID<input id="sid" required></label><label>Hostel<input id="hostel" required></label></div><div class="two"><label>Block<input id="block"></label><label>Room<input id="room"></label></div><label>Email<input id="remail" type="email" required></label><label>Password<input id="rpass" type="password" minlength="6" required></label><button class="primary">Create account</button></form>`)}
async function doRegister(e){e.preventDefault();try{await api("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:rname.value,studentId:sid.value,hostel:hostel.value,block:block.value,room:room.value,email:remail.value,password:rpass.value})});modal.classList.add("hidden");await loadMe();showToast("Account created");route()}catch(x){showToast(x.message)}}
function sell(){if(!me)return login();modalBox(`<h2>List an item</h2><form class="form" enctype="multipart/form-data" onsubmit="createListing(event)"><label>Item name<input id="ltitle" placeholder="Scientific Calculator" required></label><div class="two"><label>Category<select id="lcat">${categories.slice(1).map(c=>`<option value="${c[0]}">${c[1]}</option>`).join("")}</select></label><label>Price (₹)<input id="lprice" type="number" min="0" required></label></div><div class="two"><label>Condition<select id="lcondition"><option>New</option><option>Like New</option><option selected>Good</option><option>Used</option></select></label><label>Original price<input id="loriginal" type="number" min="0"></label></div><label>Description<textarea id="ldesc" required placeholder="Tell buyers about condition, age, accessories, reason for selling..."></textarea></label><label>Pickup location<input id="llocation" placeholder="Block B common room"></label><label>Photos <input id="limages" type="file" accept="image/*" multiple></label><label><input id="lurgent" type="checkbox"> Mark as urgent sale</label><button class="primary">Publish listing</button></form>`)}
async function createListing(e){e.preventDefault();const fd=new FormData();fd.append("title",ltitle.value);fd.append("category",lcat.value);fd.append("price",lprice.value);fd.append("condition",lcondition.value);fd.append("originalPrice",loriginal.value);fd.append("description",ldesc.value);fd.append("location",llocation.value);fd.append("urgent",lurgent.checked);[...limages.files].forEach(f=>fd.append("images",f));try{await api("/api/listings",{method:"POST",body:fd});modal.classList.add("hidden");showToast("Listing published!");location.hash="#/dashboard"}catch(x){showToast(x.message)}}
async function save(id){if(!me)return login();try{const r=await api("/api/favorites/"+id,{method:"POST"});showToast(r.saved?"Saved to wishlist":"Removed from wishlist")}catch(e){showToast(e.message)}}
async function report(id){if(!me)return login();const reason=prompt("Why are you reporting this listing?","Suspicious listing");if(!reason)return;try{await api("/api/reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({listingId:id,reason})});showToast("Report submitted")}catch(e){showToast(e.message)}}
async function contact(id){if(!me)return login();const x=await api("/api/listings/"+id);const text=encodeURIComponent(`Hi ${x.seller.name}, I found your "${x.title}" on HostelX. Is it still available?`);showToast("Opening WhatsApp...");window.open("https://wa.me/?text="+text,"_blank")}
async function dashboard(){if(!me)return login();const [mine,favs]=await Promise.all([api("/api/me/listings"),api("/api/favorites")]);app.innerHTML=`<div class="wrap"><h1>Dashboard</h1><div class="dashboard"><div class="stat">My listings<b>${mine.length}</b></div><div class="stat">Saved items<b>${favs.length}</b></div><div class="stat">Student status<b>${me.verified?"Verified":"Pending"}</b></div><div class="stat">Rating<b>⭐ ${me.rating||5}</b></div></div><div class="panel"><h2>My listings</h2>${mine.length?`<table class="table"><tr><th>Item</th><th>Price</th><th>Status</th><th>Action</th></tr>${mine.map(x=>`<tr><td>${esc(x.title)}</td><td>${money(x.price)}</td><td>${esc(x.status)}</td><td><button class="ghost" onclick="markSold('${x._id}')">Mark sold</button> <button class="danger" onclick="delItem('${x._id}')">Delete</button></td></tr>`).join("")}</table>`:`<div class="empty">You haven't listed anything yet.</div>`}</div><h2 style="margin-top:30px">Saved items</h2><div class="grid">${favs.length?favs.map(card).join(""):`<div class="empty" style="grid-column:1/-1">No saved items.</div>`}</div></div>`}
async function markSold(id){try{await api("/api/listings/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"sold"})});dashboard();showToast("Marked as sold")}catch(e){showToast(e.message)}}
async function delItem(id){if(!confirm("Delete this listing?"))return;try{await api("/api/listings/"+id,{method:"DELETE"});dashboard();showToast("Deleted")}catch(e){showToast(e.message)}}
async function admin(){if(!me||me.role!=="admin")return app.innerHTML=`<div class="empty">Admin access required.</div>`;const s=await api("/api/admin/stats");app.innerHTML=`<div class="wrap"><h1>Admin dashboard</h1><div class="dashboard"><div class="stat">Students<b>${s.students}</b></div><div class="stat">Active listings<b>${s.active}</b></div><div class="stat">Sold<b>${s.sold}</b></div><div class="stat">Open reports<b>${s.reportsOpen}</b></div></div><div class="notice">Admin tools are protected by your account role.</div></div>`}
async function route(){const p=location.hash.slice(1)||"/";if(p.startsWith("/item/"))return item(p.split("/")[2]);if(p==="/dashboard")return dashboard();if(p==="/admin")return admin();home()}
document.getElementById("authBtn").onclick=()=>me?dashboard():login();
document.getElementById("sellBtn").onclick=sell;
document.getElementById("search").addEventListener("keydown",e=>{if(e.key==="Enter"){state.q=e.target.value;location.hash="#/";home()}});
window.addEventListener("hashchange",route);
loadMe().then(route);
